# Generated by Django 6.0.7 on 2026-09-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_options_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ELECTRONIC', 'Электронно')], db_index=True, default='CASH', max_length=15, verbose_name='способ оплаты'),
        ),
    ]
