# Generated by Django 6.0.7 on 2026-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
